### ISSUE TITLE
Ongoing maintenance

### ISSUE THREAD

**Issue by nigelm** [bennie/perl-VMware-vCloud#2]
Hi,

Is there any intention to continue maintenance on this distribution?  I have emailed you in the past about contributing bug fixes, and I see there are a couple of bugs raised and several github forks with fixes in them.

In particular @ksyz has a series of bug fixes in https://github.com/ksyz/perl-VMware-vCloud/commits/master

It would be much better if the CPAN version would pick up these fixes rather than lots of private forks.

[I have a batch of work coming up which will involve a later vCloud installation (will be a new installation on whatever version is best for ongoing use - so likely 8.2 - and will need some API poking code.  I am willing to put some work in on maintaining this for CPAN release, or if its dead and buried (or just immovable) then I'll consider doing my own thing in a competing module]

  Nigel.

**Comment by bennie** [comment]
Howdy,

	My apologies for not answering sooner. Apparently this address is getting enough spam at this point that I am missing content. And that is not good.

	At this time I am no longer actively using vCloud director on my day job. So this module has been getting little love.

	If you would like to take it over, you are more than welcome to.

					- Phil

**Comment by bennie** [comment]
I've pulled @ksyz 's work into the repo.
